[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "0x5b5858"
blue = "0x3fc4de"
cyan = "0x6be4e6"
green = "0x3fdaa4"
magenta = "0xf075b5"
red = "0xec6a88"
white = "0xd5d8da"
yellow = "0xfbc3a7"

[colors.normal]
black = "0x16161c"
blue = "0x26bbd9"
cyan = "0x59e1e3"
green = "0x29d398"
magenta = "0xee64ac"
red = "0xe95678"
white = "0xd5d8da"
yellow = "0xfab795"

[colors.primary]
background = "0x1c1e26"
foreground = "0xe0e0e0"

[cursor]
blink_interval = 500

[cursor.style]
shape = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 15.0

[font.bold]
style = "Bold"

[font.bold_italic]
style = "Bold Italic"

[font.italic]
style = "Italic"

[font.normal]
family = "MesloLGS Nerd Font"
style = "Regular"

[window]
decorations = "full"
dynamic_padding = false
startup_mode = "Windowed"

[keyboard]
bindings = [
  { key = "L", mods = "Alt", chars = "\u001BF" },     # Move right one word
  { key = "H", mods = "Alt", chars = "\u001BB" },     # Move left one word
  { key = "Right", mods = "Alt", chars = "\u001BF" }, # Move right one word
  { key = "Left", mods = "Alt", chars = "\u001BB" },  # Move left one word
  { key = "K", mods = "Alt", chars = "\u001BP" },     # Search backward through history
  { key = "J", mods = "Alt", chars = "\u001BN" },     # Search forward through history
]
